include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_final_fields: true
    avoid_print: true
    prefer_const_constructors: true
    unnecessary_this: true
    prefer_if_null_operators: true
    no_leading_underscores_for_local_identifiers: true
    avoid_unnecessary_containers: true
    prefer_typing_uninitialized_variables: true
    use_build_context_synchronously: true
    prefer_relative_imports: true
